import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="h-screen">
          <div className="bg-white flex justify-between p-3">
            <h5 className="text-[#305CDE] font-bold">AskAI</h5>
            <h5 className="text-[#305CDE] font-bold">©Sai Sanjith Sivapuram</h5>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
